### ISSUE TITLE
ModuleNotFoundError: Package `llama-cpp-python` is required to be installed to use this experiment

### ISSUE THREAD

**Issue by shrijayan** [hegelai/prompttools#109]
### ⁉️ Discussion/Question

Suggested : Please use `pip install llama-cpp-python` to install the package

I am encountering difficulties installing the llama-cpp-python package in Google Colab using the command pip install llama-cpp-python. Despite following the installation instructions, the package does not seem to be recognized. This issue is hindering my ability to proceed with the experiment.

```
ModuleNotFoundError                       Traceback (most recent call last)
.ipynb Cell 3 line 1
      9 temperatures = [0.0, 1.0]
     11 call_params = dict(temperature=temperatures)
---> 13 experiment = LlamaCppExperiment(model_paths, prompts, call_params=call_params)

File ~/anaconda3/envs/llm_testing/lib/python3.10/site-packages/prompttools/experiment/experiments/llama_cpp_experiment.py:107, in LlamaCppExperiment.__init__(self, model_path, prompt, model_params, call_params)
     99 def __init__(
    100     self,
    101     model_path: List[str],
   (...)
    104     call_params: Dict[str, list[object]] = {},
    105 ):
    106     if Llama is None:
--> 107         raise ModuleNotFoundError(
    108             "Package `llama-cpp-python` is required to be installed to use this experiment."
    109             "Please use `pip install llama-cpp-python` to install the package"
    110         )
    111     self.completion_fn = self.llama_completion_fn
    112     self.model_params = model_params

```

**Comment by shrijayan** [comment]
> Can you run `! pip list | grep llama` to make sure `llama-cpp-python` is installed?

<img width="1706" alt="287717793-f8f313ca-bb6a-45e2-8fc7-6a981b26aa96" src="https://github.com/hegelai/prompttools/assets/81805145/d407183d-8cbb-4429-a01c-d53ccde894b8">

**Comment by NivekT** [comment]
Can you run `from llama_cpp import Llama` and see if that executes?

Do you have multiple `llama_cpp` in your namespace?

**Comment by NivekT** [comment]
Your model paths may be wrong. Can you verify the path in the system and your string are identical?

**Comment by shrijayan** [comment]
> Your model paths may be wrong. Can you verify the path in the system and your string are identical?

Your solution is perfect my model file name was **llama-2-7b.ggmlv.q4_0.bin?download=true** after changing that to **llama-2-7b.ggmlv.q4_0.bin** there was no issue

**Comment by NivekT** [comment]
Glad to hear it. I will close this issue. Feel free to re-open if other things come up.
