### ISSUE TITLE
Pydantic import isssues

### ISSUE THREAD

**Issue by rjarun8** [hegelai/prompttools#11]
### 🐛 Describe the bug

When running experiment.evaluate("similar_to_expected", measure_similarity) , got the following error . 

_---------------------------------------------------------------------------
PydanticImportError                       Traceback (most recent call last)
Cell In[8], line 1
----> 1 experiment.evaluate("similar_to_expected", measure_similarity)

File G:\RajArun\os\PromptTools\env\Lib\site-packages\prompttools\experiment\experiment.py:172, in Experiment.evaluate(self, metric_name, eval_fn, input_pairs)
    169     return
    170 for i, result in enumerate(self.results):
    171     # Pass the messages and results into the eval function
--> 172     score = eval_fn(
    173         input_pairs[self.argument_combos[i][1]]
    174         if input_pairs
    175         else self.argument_combos[i][1],
    176         result,
    177         {
    178             name: self.scores[name][i]
    179             for name in self.scores.keys()
    180             if name is not metric_name
    181         },
    182     )
    183     self.scores[metric_name].append(score)
    184     if self.use_scribe:

Cell In[7], line 17, in measure_similarity(messages, results, metadata)
     10 def measure_similarity(
     11     messages: List[Dict[str, str]], results: Dict, metadata: Dict
     12 ) -> float:
     13     """
     14     A simple test that checks semantic similarity between the user input
     15     and the model's text responses.
     16     """
---> 17     distances = [
     18         similarity.compute(EXPECTED[messages[1]["content"]], response)
     19         for response in extract_responses(results)
     20     ]
     21     return min(distances)

Cell In[7], line 18, in <listcomp>(.0)
     10 def measure_similarity(
     11     messages: List[Dict[str, str]], results: Dict, metadata: Dict
     12 ) -> float:
     13     """
     14     A simple test that checks semantic similarity between the user input
     15     and the model's text responses.
     16     """
     17     distances = [
---> 18         similarity.compute(EXPECTED[messages[1]["content"]], response)
     19         for response in extract_responses(results)
     20     ]
     21     return min(distances)

File G:\RajArun\os\PromptTools\env\Lib\site-packages\prompttools\utils\similarity.py:53, in compute(doc1, doc2, use_chroma)
     51 def compute(doc1, doc2, use_chroma=True):
     52     if use_chroma:
---> 53         return _from_chroma(doc1, doc2)
     54     else:
     55         return _from_huggingface(doc1, doc2)

File G:\RajArun\os\PromptTools\env\Lib\site-packages\prompttools\utils\similarity.py:43, in _from_chroma(doc1, doc2)
     42 def _from_chroma(doc1, doc2):
---> 43     chroma_client = _get_chroma_client()
     44     collection = chroma_client.create_collection(name="test_collection")
     45     collection.add(documents=[doc1], ids=["id1"])

File G:\RajArun\os\PromptTools\env\Lib\site-packages\prompttools\utils\similarity.py:27, in _get_chroma_client()
     25 def _get_chroma_client():
     26     if len(CHROMA_CLIENT) == 0:
---> 27         import chromadb
     29         CHROMA_CLIENT.append(chromadb.Client())
     30     return CHROMA_CLIENT[0]

File G:\RajArun\os\PromptTools\env\Lib\site-packages\chromadb\__init__.py:1
----> 1 import chromadb.config
      2 import logging
      3 from chromadb.telemetry.events import ClientStartEvent

File G:\RajArun\os\PromptTools\env\Lib\site-packages\chromadb\config.py:1
----> 1 from pydantic import BaseSettings
      2 from typing import Optional, List, Any, Dict, TypeVar, Set, cast, Iterable, Type
      3 from typing_extensions import Literal

File G:\RajArun\os\PromptTools\env\Lib\site-packages\pydantic\__init__.py:206, in __getattr__(attr_name)
    204 dynamic_attr = _dynamic_imports.get(attr_name)
    205 if dynamic_attr is None:
--> 206     return _getattr_migration(attr_name)
    208 from importlib import import_module
    210 module = import_module(_dynamic_imports[attr_name], package=__package__)

File G:\RajArun\os\PromptTools\env\Lib\site-packages\pydantic\_migration.py:279, in getattr_migration.<locals>.wrapper(name)
    277     return import_string(DEPRECATED_MOVED_IN_V2[import_path])
    278 if import_path == 'pydantic:BaseSettings':
--> 279     raise PydanticImportError(
    280         '`BaseSettings` has been moved to the `pydantic-settings` package. '
    281         f'See https://docs.pydantic.dev/{VERSION}/migration/#basesettings-has-moved-to-pydantic-settings '
    282         'for more details.'
    283     )
    284 if import_path in REMOVED_IN_V2:
    285     raise PydanticImportError(f'`{import_path}` has been removed in V2.')

PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.0.2/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.0.2/u/import-error_

**The issue occurred when creating the chroma client in prompttools due to migrations pydantic settings migration.**

PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.0.2/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.0.2/u/import-error

The above required changes in chromadb .

PR raised to address this : https://github.com/chroma-core/chroma/pull/775

**Comment by steventkrawczyk** [comment]
Thanks for opening that PR in Chroma's repo @rjarun8! Please keep us posted for when it lands 🙏
