### ISSUE TITLE
MindsDB integration

### ISSUE THREAD

**Issue by steventkrawczyk** [hegelai/prompttools#30]
### 🚀 The feature

MindsDB is a server for AI logic
https://github.com/mindsdb/mindsdb

We can add a MindsDbExperiment to test that AI logic

### Motivation, pitch

MindsDB is a large OSS project for AI orchestration, and it would be good to support them with our test framework

### Alternatives

N/A

### Additional context

We have gotten a few users asking about MindsDB

**Comment by NivekT** [comment]
Added in #37 thanks to @HashemAlsaket!!
