### ISSUE TITLE
Are any metrics/ telemetry data collected?

### ISSUE THREAD

**Issue by TheNotary** [hegelai/prompttools#45]
### ⁉️ Discussion/Question

Hi I read the FAQ but it got me wondering if it was intentional that the a "no data collection" policy wasn't listed.

**Comment by steventkrawczyk** [comment]
Hey @TheNotary, great question!

We don't collect any metrics or telemetry data, and we'd love to make that explicit with a "no data collection" policy. Do you have any examples of such policies? Feel free to share it here, or open a PR with the policy, and we'll take a look and get that merged in.

**Comment by TheNotary** [comment]
Just a plain English indication in the FAQ that "No metrics, telemetry, or usage data are collected whatsoever when using this software" would fit well and give new comers confidence I think.

**Comment by NivekT** [comment]
Thanks for letting us know. We will update the README to emphasize that we don't collect any data.
