### ISSUE TITLE
Add support for LanceDB

### ISSUE THREAD

**Issue by NivekT** [hegelai/prompttools#48]
### 🚀 The feature

[LanceDB](https://lancedb.com/) is a developer-friendly, serverless vector database.

### Motivation, pitch

We can integrate with its APIs to allow experimentation on various configurations and look at its performance.

### Additional context

You can have a look at the Chroma or Weaviate for inspiration. If you would like to work on this, comment and let us know! We will be more than happy to support you.

**Comment by HashemAlsaket** [comment]
Heads up- need to have `Rust` installed. It's a dependency for `tantivy-py` which is a dependency for `LanceDB`.

**Comment by NivekT** [comment]
This is being worked on by myself and @AyushExel from Lance

**Comment by AyushExel** [comment]
Thanks for the PR
@HashemAlsaket @NivekT tantivy is not a compulsory requirement. Lancedb doesn't require any extra setup or auth other than `pip install lancedb`

**Comment by HashemAlsaket** [comment]
I was unable to search a table without `tantivy`:
![image](https://github.com/hegelai/prompttools/assets/17466553/0b4382f0-1619-486d-9aca-cbb72c744997)

**Comment by AyushExel** [comment]
You're using FTS. FTS requires tantivy, vector search doesn't

**Comment by HashemAlsaket** [comment]
Ah ok, thanks for the clarification!

**Comment by NivekT** [comment]
Closed by #71
