### ISSUE TITLE
LangChain Support

### ISSUE THREAD

**Issue by steventkrawczyk** [hegelai/prompttools#5]
Add Harnesses and Experiments to support testing LangChains natively.

Components will include:
* Low level chain and agent experiments
* Chain and agent harnesses
* Step-by-step visualizations, and support for evaluating intermediate outputs

**Comment by AAbbhishekk** [comment]
I can collaborate on it.

**Comment by steventkrawczyk** [comment]
@AAbbhishekk Awesome! I've added you to the issue. Feel free to raise a PR to get started, or ask any questions you have on this issue / in the discord: https://discord.gg/72a9xh5Z7P
