### ISSUE TITLE
Add Qdrant Vector database support 

### ISSUE THREAD

**Issue by rafidude** [hegelai/prompttools#52]
### 🚀 The feature

Qdrant (https://qdrant.tech/) is a high-performance vector DB.

### Motivation, pitch

We are using Qdrant and found its performance much better than other Vector DBs. Please see the benchmarks at https://qdrant.tech/benchmarks/.

**Comment by NivekT** [comment]
Hi @rafidude, thanks for suggesting this. We have a similar issue (#47) already opened. I will consolidate the discussion over there. Do let us know if you are interested to work on the feature. Thanks!
