### ISSUE TITLE
PyPI release missing utils

### ISSUE THREAD

**Issue by HashemAlsaket** [hegelai/prompttools#7]
### 🐛 Describe the bug

Was able to move `utils` folder from git clone to get the example in README to work. But `utils` is missing in the PyPI release.

![hegel_missing_utils](https://github.com/hegelai/prompttools/assets/17466553/c77447ef-08d2-413a-bf3d-9438ef58e63d)

**Comment by steventkrawczyk** [comment]
Thanks for the heads up! This should take care of it: https://github.com/hegelai/prompttools/commit/9c6675e1597b85c39a2f66f63b63ad522681d5f5
