### ISSUE TITLE
Replicate integration 

### ISSUE THREAD

**Issue by steventkrawczyk** [hegelai/prompttools#73]
### 🚀 The feature

Replicate supports serverless inference for LLMs: https://replicate.com/collections/language-models

We should create a replicate experiment. 

### Motivation, pitch

Easy way to test OSS LLMs, good to compare to Huggingface hosted endpoints

**Comment by NivekT** [comment]
We have integrated with Replicate. You can run various models, such as [Llama 2](https://github.com/hegelai/prompttools/blob/main/examples/notebooks/ReplicateLlama2.ipynb) and [Stable Diffusion](https://github.com/hegelai/prompttools/blob/main/examples/notebooks/image_experiments/ReplicateStableDiffusion.ipynb).

If any model doesn't work with our `ReplicateExperiment`, please feel free to comment here or open another issue.
