### ISSUE TITLE
Error in experiment.evaluate() in introductory example OpenAIChatExperiment.ipynb

### ISSUE THREAD

**Issue by davidtan-tw** [hegelai/prompttools#76]
Hi folks, thanks for creating this tool.

I'm trying out `prompttools` and was following the introductory example (OpenAIChatExperiment.ipynb) listed on the [quickstart](https://prompttools.readthedocs.io/en/latest/quickstart.html) page and encountered this error. I can reproduce the error locally and on the provided [Colab notebook](https://colab.research.google.com/drive/1YVcpBew8EqbhXFN8P5NaFrOIqc1FKWeS?usp=sharing#scrollTo=e80dfeec)

### 🐛 Describe the bug

This is the line that raises an error:
```
experiment.evaluate("similar_to_expected", similarity.evaluate, expected="George Washington")
```

And this is the error: `TypeError: evaluate() missing 2 required positional arguments: 'response' and 'metadata'`

<img width="1573" alt="image" src="https://github.com/hegelai/prompttools/assets/49261334/7db06c25-ddca-4dc9-b857-0cd4d9ae4f2f">

**Comment by davidtan-tw** [comment]
Managed to fix error by importing the right function (`semantic_similarity`) from the right package (`prompttools.utils`). See fix:

<img width="1397" alt="image" src="https://github.com/hegelai/prompttools/assets/49261334/722d6f67-4616-4cae-b202-4fdd9248561b">

Would it be right to say that the [OpenAIChatExperiment.ipynb](https://colab.research.google.com/drive/1YVcpBew8EqbhXFN8P5NaFrOIqc1FKWeS?usp=sharing#scrollTo=e80dfeec) was importing the wrong function (`prompttools.utils.similarity.evaluate`)?

**Comment by steventkrawczyk** [comment]
Hey David, thanks for trying prompttools and mentioning these issues. I believe everything's up to date for that example on the HEAD of `main`

https://github.com/hegelai/prompttools/blob/main/examples/notebooks/OpenAIChatExperiment.ipynb

We'll make the error handling better.
