### ISSUE TITLE
Examples are mixed/stacking up

### ISSUE THREAD

**Issue by HashemAlsaket** [hegelai/prompttools#81]
### 📚 The doc issue

Under `examples/notebooks` there are many example notebooks varying from LLMs, text, images, DBs. Should we store them in separate directories?

### Suggest a potential fix

```
├── examples
├── ├── notebooks
├── ├── ├── benchmark
├── ├── ├── image_experiments
├── ├── ├── ├── StableDiffusionExperiment.ipynb
├── ├── ├── llm_experiments
├── ├── ├── ├── LlamaCppExperiment.ipynb
├── ├── ├── db_experiments
├── ├── ├── ├── LanceDBExperiment.ipynb
├── ├── ├── audio_experiments
├── ├── ├── ├── MusicGenExperiment.ipynb
├── ├── ├── video_experiments
```

**Comment by NivekT** [comment]
This is definitely better in the long term. The downside of updating the path is that previous posts (on social media, etc) might have broken links.

We will also have to make sure all links within the repo (e.g. doc, README) have the updated links.

**Comment by NivekT** [comment]
One idea: we can move the notebooks and use symlinks to keep the previous links working.

**Comment by NivekT** [comment]
I have moved the non-LLM examples to subfolders. Let's close this for now. Feel free to re-open if anyone has concerns about this.
