### ISSUE TITLE
Support for Google Vertex AI

### ISSUE THREAD

**Issue by richardguinness** [hegelai/prompttools#90]
### 🚀 The feature

Support for Google's PaLM 2 API is documented, but there's no mention of Google's Vertex AI model support (e.g. chat-bison). Please add support for this.

### Motivation, pitch

Google's Vertex AI offerings are appropriate where data isolation is required. We use Vertex AI models internally and would like to use Prompt Tools in conjunction with them

**Comment by NivekT** [comment]
@richardguinness Thank you for opening this issue. 

I just added [Google Vertex Chat experiment](https://github.com/hegelai/prompttools/blob/main/prompttools/experiment/experiments/google_vertex_chat_experiment.py) with an [usage example](https://github.com/hegelai/prompttools/blob/main/examples/notebooks/GoogleVertexChatExperiment.ipynb).

Let us know if this works for your use case. If you are interested in other types of models (e.g. text, code), let us know or feel free to open a PR to add those.

Note that you will have to install from source until we push a new version of the package.
