### ISSUE TITLE
Error when running promptools

### ISSUE THREAD

**Issue by filopedraz** [hegelai/prompttools#94]
### 🐛 Describe the bug

After installing the dependencies and running the app with `streamlit` I get: 

```txt
ModuleNotFoundError: No module named 'pyperclip'
```

Both `streamlit` and `pyperclip` don't seem to be part of the [dependencies](https://github.com/hegelai/prompttools/blob/main/requirements.txt).

**Comment by steventkrawczyk** [comment]
Thanks for the heads up! We have a separate requirements file for the playground at https://github.com/hegelai/prompttools/blob/main/prompttools/playground/requirements.txt. We'll figure out a better way to surface this requirement.
